dna = "TTTTAACCAATCCTGGAGCCAAGACAATCCTGGACAAAATTGAGGATTGTGAGGATTGCAATCCTGGCAATCCTGGAGCCAAGATGAGGATTGCAATCCTGGACAAAATCAATCCTGGTTTTAACTGAGGATTGCAATCCTGGTGAGGATTGCAATCCTGGAGCCAAGAACAAAATAGCCAAGAAGCCAAGACAATCCTGGTTTTAACTTTTAACAGCCAAGATGAGGATTGCAATCCTGGAGCCAAGATGAGGATTGACAAAATACAAAATACAAAATTTTTAACCAATCCTGGTTTTAACTGAGGATTGACAAAATAGCCAAGAAGCCAAGAACAAAATACAAAATAGCCAAGAAGCCAAGATGAGGATTGTTTTAACCAATCCTGGAGCCAAGATGAGGATTGACAAAATTGAGGATTGAGCCAAGAACAAAATAGCCAAGACAATCCTGGACAAAATCAATCCTGGTGAGGATTGAGCCAAGAAGCCAAGATTTTAACTTTTAACACAAAATCAATCCTGGTTTTAACTTTTAACACAAAATCAATCCTGGAGCCAAGATGAGGATTGACAAAATAGCCAAGACAATCCTGGACAAAATTTTTAACCAATCCTGGACAAAATTGAGGATTGACAAAATCAATCCTGGCAATCCTGGCAATCCTGGTTTTAACTGAGGATTGACAAAATACAAAATAGCCAAGAAGCCAAGAACAAAATAGCCAAGAACAAAATTGAGGATTGTTTTAACTGAGGATTGTTTTAACCAATCCTGGCAATCCTGGACAAAATACAAAATTGAGGATTGCAATCCTGGTTTTAACCAATCCTGGTGAGGATTGCAATCCTGGTGAGGATTGTGAGGATTGTGAGGATTGAGCCAAGA"
kmer_len = 12
kmer_list = []

for i in range(len(dna)-kmer_len+1):
	kmer_list.append(dna[i:i+kmer_len])


dic_kmers = []
dic_count = []


for kmer in kmer_list:
	found = 0
	for i in range(len(dic_kmers)):
		if kmer == dic_kmers[i]:
			dic_count[i] = dic_count[i] + 1
			found = 1
	
	if found == 0:
		dic_kmers.append(kmer)
		dic_count.append(1)


highest_value = 0
highest_positions = []		
for entry in range(len(dic_kmers)):
	if highest_value < dic_count[entry]:
		highest_positions = []
		highest_positions.append(dic_kmers[entry])
		highest_value = dic_count[entry]
	elif highest_value == dic_count[entry]:
		highest_positions.append(dic_kmers[entry])

	
		
tempW = open('output_BA1B.txt','w')
for word in range(len(highest_positions)):
	tempW.write((str(highest_positions[word]) + " "))
tempW.close()