#Have to manually parse s1 and s2, could make a parser which appends to sList, have to change for loop to sList[a][i] to use strings.
s1 = "ATTGGCCCCAATCTTTCGCGTCAGCCACCATTTGGCCATGGGTAACATGGTCGCCAGGCATCGTCGTTCGTTGGAGAACATAATCGATTTCCGTCCTTCGGACGTGTGAGGCTGCCACGTGGTGCCACCAGAATCGCAAGTATCGCTGGGTATCGGCGGCACCGCGAGGCGTTGCTAAACACATAAGGATATCTATTACGTGATTTTTGCTATGGCATCTAAGACTGCTTACATGGGGCTGACTGTGTGCCGCAGTTGGGGCGCTAGCACTTCTTTGCTCTCGACGGCGCTCTTCTCACATTGGATAACAGGAAACTACCCGGCCGGATTGGGCACTTAAATTGAATTAGTAGCAGTGTCGGATTACCCACCACCTGTCACACAGTTGACTTACTGGGTAATGGGCCCCGCTATTGCCATGTTCCGTTCACGGCAGATGACATGTGTTCACGTGTTCCAGCGGCTGTATTATATGAAGACCCCCTCTTCGGTGCTCATCCTGGAGCAACCTGTGAAGGTTGCCCTTTCCGCATAGCGGCGACTGGTATTGATACACTCACCCGTAGAGGTTCTGTTACTTCTATACCCCTTACTATTTTGGGCATGACCCTCACTGCTCAGCCGCGAGTTTCAAATTGATAATACTTTTGTGTCAAATCATCCGGGAATTAAGTTTCTCAACTATAAATACTTTAAAGTTCTGTAAGTCTTTCCAAGGTAAATCCTCCGACCTCAGTACCCTCCAGATACCATATAGCTATCTACAAAGGGAAGAAGTGCCTGTGCTCGATAAGCGCCATAGAGGTAGGGCCAACCGCTTGTCGGAGCGGAATGCTCACATTACCTCGCGACTCGCGAAGCGAGGGTAACGGATATGTTAGTCAGGCCTACCTAGAAACTAACGTTCGCCTCAGTACTACGTCAGGCCCTGTACGACCGTACTGATAGA"
s2 = "GTTGGCCCTCGCCTTTTGCGCCAACCACCAATCAGGCACGGGTGATCTGGCCACCAGGCTCCGTCGGTCACTAAGAAATAGAGGAAACTTCCATACTTCATGTGAGTGAGGCCGGTGTGTGGATTCCTCAGAACCACAACGACCGCTGGGAACCGGAGGTACCGCGGGACGTTTCTAACCACAAATGGATATATGCTACGTTAGTCCTGCTATAGCGCATTAGACTGCTCAAACGCGGCTGACTGTGTATCACATCAGGGTTGCCACTACCGTGTTCCTCCCAATAGCGCTGTTCTTGCATTGTACAGCAGGAGAATATCCGTCCGAATTGGACTCTTAAACCGAATTAGTGGCAATATTGGACTCCCTACCACCTGTCTCACGATTACCTTACCCGGCGACAGGTCCGGCCGTTGTCATGCTCTGTTCAGGACGGACGGCCTTTGTTTGCGTATTTTAGCGGTTACAGCATACGAAGATCCTCTCTTTAGTGCTCATCCTGGCGCAACTTATGAGAATTACCCTGTTTGCATGGCCGCGTCTCATGTGGCGATACTGACTCGTAGAGGCCTCACTACGTCGATACCCCTCGCTATCCAGGGCATAACCCGCATTACCCACCCGCTCGCTTCAAGTTGGTAGTCCTCCTGTGGCGTGTCACACGGGAAATAAGTCTTTCTACCTTAAATACTCTAAATTTCGATAAGTTTTTCCCAAGAAAGTTCCCCGATATCGTTATGCCCCAGACACTAGGTAACTAGCTGTAAAGGGAAAGAGTGCGCGTGCTCGACAAGAACTACATAGGTAAGGCCAACCACCTACTGGAACGGAAAGCTCATATTGCCTTGCGGTCCGTAAATGTAGGATGGTAAACATCTTAATCAACCGTACCTAGGAACTATCGTTTAGCATATTCCTACACCGAACCCTGCACGACCGCATTGATAGA"

transversion = 0
transition = 0 
for i in range(len(s1)):#checks every event for transitions/transversions, could make 2 big if(s) instead, with ((A or G)and(C or T)) or (reverse)
	if s1[i] != s2[i]:
		print i, s1[i], s2[i]
	if s1[i] == "A" and s2[i] == "T":
		print i, s1[i], s2[i], "Ver"
		transversion += 1.0
	elif s1[i] == "A" and s2[i] == "C":
		print i, s1[i], s2[i], "Ver"
		transversion += 1.0
	elif s1[i] == "G" and s2[i] == "C":
		print i, s1[i], s2[i], "Ver"
		transversion += 1.0
	elif s1[i] == "G" and s2[i] == "T":
		print i, s1[i], s2[i], "Ver"
		transversion += 1.0	
	elif s1[i] == "T" and s2[i] == "A":
		print i, s1[i], s2[i], "Ver"
		transversion += 1.0		
	elif s1[i] == "T" and s2[i] == "G":
		print i, s1[i], s2[i], "Ver"
		transversion += 1.0		
	elif s1[i] == "C" and s2[i] == "A":
		print i, s1[i], s2[i], "Ver"
		transversion += 1.0		
	elif s1[i] == "C" and s2[i] == "G":
		print i, s1[i], s2[i], "Ver"
		transversion += 1.0				
	
	elif s1[i] == "A" and s2[i] == "G":
		print i, s1[i], s2[i], "Sit"
		transition += 1.0
	elif s1[i] == "G" and s2[i] == "A":
		print i, s1[i], s2[i], "Sit"
		transition += 1.0	
	elif s1[i] == "C" and s2[i] == "T":
		print i, s1[i], s2[i], "Sit"
		transition += 1.0	
	elif s1[i] == "T" and s2[i] == "C":
		print i, s1[i], s2[i], "Sit"
		transition += 1.0				
print float(transition)/float(transversion)